### ISSUE TITLE
after i run npm test

### ISSUE THREAD

**Issue by kinkeyluja** [evgomes/vidly-api#10]
PS C:\Users\ASUS\vidly-api-master> npm test
npm ERR! code ENOENT
npm ERR! syscall open
npm ERR! path C:\Users\ASUS\vidly-api-master\package.json
npm ERR! errno -4058
npm ERR! enoent ENOENT: no such file or directory, open 'C:\Users\ASUS\vidly-api-master\package.json'
npm ERR! enoent This is related to npm not being able to find a file. 
npm ERR! enoent

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\ASUS\AppData\Roaming\npm-cache\_logs\2021-06-16T12_38_50_223Z-debug.log

**Comment by ksaurabh4** [comment]
It is working fine in my system!
![image](https://user-images.githubusercontent.com/36674657/122222118-93e8ed00-cecf-11eb-9fa1-82aa007ce201.png)

**Comment by kinkeyluja** [comment]
Error: Cannot find module 'C:\Users\ASUS\vidly-api-master\index.js'   
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:885:15)
    at Function.Module._load (internal/modules/cjs/loader.js:730:27)  
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
    at internal/main/run_main_module.js:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
PS C:\Users\ASUS\vidly-api-master> npm i module 
npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
npm WARN enoent ENOENT: no such file or directory, open 'C:\Users\ASUS\vidly-api-master\package.json'
npm WARN vidly-api-master No description
npm WARN vidly-api-master No repository field.
npm WARN vidly-api-master No README data
npm WARN vidly-api-master No license field.

npm ERR! code EPERM
npm ERR! syscall rename
npm ERR! path C:\Users\ASUS\vidly-api-master\node_modules\source-map\package.json.1615557389
npm ERR! dest C:\Users\ASUS\vidly-api-master\node_modules\source-map\package.json
npm ERR! errno -4048
npm ERR! Error: EPERM: operation not permitted, rename 'C:\Users\ASUS\vidly-api-master\node_modules\source-map\package.json.1615557389' -> 'C:\Users\ASUS\vidly-api-master\node_modules\source-map\package.json'  
npm ERR!  [OperationalError: EPERM: operation not permitted, rename 'C:\Users\ASUS\vidly-api-master\node_modules\source-map\package.json.1615557389' -> 'C:\Users\ASUS\vidly-api-master\node_modules\source-map\package.json'] {
npm ERR!   cause: [Error: EPERM: operation not permitted, rename 'C:\Users\ASUS\vidly-api-master\node_modules\source-map\package.json.1615557389' -> 'C:\Users\ASUS\vidly-api-master\node_modules\source-map\package.json'] {
npm ERR!     errno: -4048,
npm ERR!     code: 'EPERM',
npm ERR!     syscall: 'rename',
npm ERR!     path: 'C:\\Users\\ASUS\\vidly-api-master\\node_modules\\source-map\\package.json.1615557389',
npm ERR!     dest: 'C:\\Users\\ASUS\\vidly-api-master\\node_modules\\source-map\\package.json'
npm ERR!   },
npm ERR!   errno: -4048,
npm ERR!   code: 'EPERM',
npm ERR!   syscall: 'rename',
npm ERR!   path: 'C:\\Users\\ASUS\\vidly-api-master\\node_modules\\source-map\\package.json.1615557389',
npm ERR!   dest: 'C:\\Users\\ASUS\\vidly-api-master\\node_modules\\source-map\\package.json'
npm ERR! }
npm ERR!
npm ERR! The operation was rejected by your operating system.
npm ERR! It's possible that the file was already in use (by a text editor or antivirus),
npm ERR!
npm ERR! If you believe this might be a permissions issue, please double-check the
npm ERR! permissions of the file and its containing directories, or try running
npm ERR! the command again as root/Administrator.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\ASUS\AppData\Roaming\npm-cache\_logs\2021-06-16T12_52_40_092Z-debug.log
PS C:\Users\ASUS\vidly-api-master> node index.js
internal/modules/cjs/loader.js:888
  throw err;
  ^

Error: Cannot find module 'C:\Users\ASUS\vidly-api-master\index.js'   
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:885:15)
    at Function.Module._load (internal/modules/cjs/loader.js:730:27)  
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
    at internal/main/run_main_module.js:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
PS C:\Users\ASUS\vidly-api-master>

**Comment by ksaurabh4** [comment]
Show me the file section in your code editor.. as in your error, folder name showing **_vidly-api-master_** but I have **vidly-api** only
![image](https://user-images.githubusercontent.com/36674657/122229658-94d14d00-ced6-11eb-9f7c-9ac439bdb3f7.png)

**Comment by kinkeyluja** [comment]
i dont have .git file

**Comment by ksaurabh4** [comment]
.git file is hidden by default. there is no issue with that
